// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto;

#nullable disable

namespace Proyecto.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20240402153922_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("78d2005c-20d4-4ada-980c-4e990fe23114"),
                            Descripcion = "",
                            Nombre = "Actividades Pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("78d2005c-20d4-4ada-980c-4e990fe23115"),
                            Descripcion = "",
                            Nombre = "Actividades Privadas",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("78d2005c-20d4-4ada-980c-4e990fe23116"),
                            Descripcion = "",
                            Nombre = "Actividades Personales",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("Proyecto.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("78d2005c-20d4-4ada-980c-4e990fe23119"),
                            CategoriaId = new Guid("78d2005c-20d4-4ada-980c-4e990fe23114"),
                            Descripcion = "",
                            FechaCreacion = new DateTime(2024, 4, 2, 12, 39, 22, 469, DateTimeKind.Local).AddTicks(409),
                            Prioridad = 1,
                            Titulo = "Actividades Pendientes.Estudiar"
                        },
                        new
                        {
                            TareaId = new Guid("78d2005c-20d4-4ada-980c-4e990fe23118"),
                            CategoriaId = new Guid("78d2005c-20d4-4ada-980c-4e990fe23115"),
                            Descripcion = "",
                            FechaCreacion = new DateTime(2024, 4, 2, 12, 39, 22, 469, DateTimeKind.Local).AddTicks(439),
                            Prioridad = 0,
                            Titulo = "Actividades Privadas.terminar Peli"
                        },
                        new
                        {
                            TareaId = new Guid("78d2005c-20d4-4ada-980c-4e990fe23117"),
                            CategoriaId = new Guid("78d2005c-20d4-4ada-980c-4e990fe23116"),
                            Descripcion = "",
                            FechaCreacion = new DateTime(2024, 4, 2, 12, 39, 22, 469, DateTimeKind.Local).AddTicks(444),
                            Prioridad = 2,
                            Titulo = "Actividades Personales.pilates"
                        });
                });

            modelBuilder.Entity("Proyecto.Models.Tarea", b =>
                {
                    b.HasOne("Proyecto.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Proyecto.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
